In [2]:
import numpy as np
#넘파이

In [3]:
#10개의 난수 생성
data=np.random.rand(10)
print(data)

[0.33405466 0.4827559  0.76438098 0.46372662 0.05631761 0.88459638
 0.94631177 0.44220109 0.2694387  0.40370112]


In [8]:
data1=[1,2,3,4,5]
arr1=np.array(data1)
print(data1)
print(arr1)
print(type(data1))
print(type(arr1))
print(arr1.shape)

[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>
(5,)


In [11]:
data2=[[1,2,3],[4,5,6]]
arr2=np.array(data2)
print(arr2)
print(type(arr2))
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
(2, 3)


In [16]:
x=np.random.rand(5)
y=np.random.rand(5)
z=np.maximum(x,y)
z2=np.minimum(x,y)
print(x);print(y);print(z);print(z2)

[0.20229586 0.85386162 0.69582394 0.41814717 0.61954427]
[0.89936932 0.22790315 0.71936915 0.66388853 0.39788981]
[0.89936932 0.85386162 0.71936915 0.66388853 0.61954427]
[0.20229586 0.22790315 0.69582394 0.41814717 0.39788981]


In [18]:
z=[]

for i in range(0,5,1):
    if(x[i]>y[i]):
        z.append(x[i])
    else:
        z.append(y[i])
print(z)        


[0.8993693217351151, 0.8538616236206072, 0.7193691502725115, 0.6638885311213787, 0.619544271861304]


In [26]:
data=[[4,2,8],[5,1,6],[7,3,9]]
arr1=np.array(data)
print(arr1)

[[4 2 8]
 [5 1 6]
 [7 3 9]]


In [29]:
print(arr1.sum())
print(arr1.mean())
print(arr1.sum(axis=0))
print(arr1.sum(axis=1))
#행(axis=0),열(axis=1) 정렬
print(np.sort(arr1,axis=1))

45
5.0
[16  6 23]
[14 12 19]
[[2 4 8]
 [1 5 6]
 [3 7 9]]


In [30]:
data=[1,2,1,3,2]
arr1=np.array(data)
print(arr1)

[1 2 1 3 2]


In [31]:
print(np.unique(arr1))

[1 2 3]
